name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc

      - name: Run DVC Pipeline
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}  # Pass secret here
        run: |
          # Set the DVC remote configuration with the token
          dvc remote modify myremote --local user "$DAGSHUB_TOKEN"
          dvc remote modify myremote --local password "$DAGSHUB_TOKEN"

          # Run the DVC pipeline (re-run the stages)
          dvc repro

          # Now you can push/pull with DVC
          dvc push -r myremote

      - name: Run model tests
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          python -m unittest tests/model_test.py
